## Authors' affiliations

^1^ Indian Ocean Tuna Commission (IOTC) (present affiliation)

\(^\dagger\) Corresponding author: [IOTC-Statistics@fao.org](IOTC-Statistics@fao.org)

^2^ Overseas Fisheries Development Council

^3^ Shanghai Ocean University

^4^ Fisheries Resources Institute

^5^ Délégation Ifremer Océan Indien

^6^ Tokyo University of Marine Science and Technology

^7^ Independent consultant

## Abstract

We collated a data set of almost half a million observations of fork length and round weight for albacore spanning more than two decades and spreading across the fishing grounds of albacore over the whole Indian Ocean. Most data were collected on fresh fish at sea on large-scale longliners. First, we fitted generalized additive models that showed that the relationship between length and weight varied with sex, space, and time while the fleet and fishery also had an effect on morphometric parameters of Indian Ocean albacore. Secondly, we used linear models to develop statistical relationships between fork length and round weight for operational use and showed that the large areas used for deriving albacore abundance indices for the assessment had a significant effect to explain the observed variability in weights, although the percentage of variation was very small. Weights predicted in the northeastern part of the Indian Ocean were found to be higher than in other regions. Finally, fitting a univariate linear model only considering fork length as covariate showed that the relationships used for the assessments conducted in 2019 and 2022 overestimated albacore's weight.

**Keywords:** morphometrics, fisheries observer programs, regional observer scheme, tuna fisheries

\pagebreak 