# Introduction

Morphometric relationships and conversion factors are instrumental in fisheries science to harmonize size-frequency data and compute weight from length so as to derive raising factors for extrapolation, estimate the species composition of the catch from size-frequency samples, and compute reporting coverage for catches reported in numbers. The current IOTC official relationship between fork length (FL) and round weight (RD) for Indian Ocean albacore (_Thunnus alalunga_) has been derived from fish sampled between 1990 and 1991 from the large-scale drifting gillnet fishery that operated in the south-central Indian Ocean [@Hsu1999]. Meanwhile, the relationship used in the last stock assessment in 2019 was based on albacore caught in the southeast Atlantic Ocean in the early 1990s [@Penney1994]. During the last Working Party on Temperate Tuna ([WPTmT07(AS)](https://iotc.org/meetings/7th-working-party-temperate-tuna-wptmt07-assessment-meeting)), @Kitakado2019 developed an alternative relationship based a large data set of data collected by scientific observers onboard Japanese longliners during 2012-2016 that predicts lower overall fish weights (by 10-15%) compared to Penney (1994) and was used for sensitivity analysis runs of the model [@Langley2019]. Since then, several morphometric data have been collected for albacore through different fisheries monitoring programs and research projects conducted in the Indian Ocean [@Setyadji2012;@Dhurmeea2016;@Bodin2018;@Bonhommeau2019].

In this context, the overarching objective of the study was to develop a statistical relationship between fork length and round weight for albacore based on the collation of different data sources available from a range of fisheries catching albacore across the whole Indian Ocean. First, we assessed the factors affecting the variability in weight measurements with generalized additive models [@Hastie1990]. Second, we fitted mean regression models to the data and assessed the influence of spatio-temporal factors, sex, fishery, and fleet on the weights solely predicted from fish length.

<!-- Third, we developed a new univariate relationship between fork length and round weight for Indian Ocean albacore and estimated its impact on the average weight of albacore in the catch for the strata sampled for size. -->

