# Materials & Methods

Albacore morphometric data were collated from different sources and harmonized according to a common standardized format (**Table \@ref(tab:DataFieldsDefinitions)**). The original data sets were collected as part of (i) historical longline observer programs from Korea and the UK [@IOTC2005;@Geehan2013], (ii) the Japan national scientific observer program for longliners for which data were submitted in electronic format to the Secretariat as part of the IOTC Regional Observer Scheme (ROS), (iii) the pelagic longline observer programs from China and Taiwan,China, (iv) research projects conducted on albacore by the University of Mauritius (UoM) and the French national Research Institute for Sustainable Development (IRD) [@Dhurmeea2016;@Bodin2018], and (v) routine monitoring program on the biology of large pelagics conducted by the French national research institute Ifremer in Reunion Island [@Bonhommeau2018;@Bonhommeau2019].

Observer data from Chinese longliners were filtered based on the visual exam of the scatterplots between fork length and round weight for each trip as some weight measurements were made visually by some observers. A more thorough quality and control procedure was applied to select the good-quality observer data collected onboard Taiwanese longliners. The spatial resolution considered for the study was a grid of 5x5-degree squares although the spatial information was larger for 48 samples collected at sea in the Chagos archipelago and 70 samples collected from the semi-industrial longline fishery based in Reunion Island. 

After filtering the data, the total data set was comprised of `r prettyNum(ALB_FL_RD[, .N], big.mark = ",")` albacore caught between `r min(ALB_FL_RD$YEAR, na.rm = TRUE)` and `r max(ALB_FL_RD$YEAR, na.rm = TRUE)` from longline, baitboat, line, and purse seine fisheries (**Table \@ref(tab:SamplingDesignTableSourceFisheryGroup)**). The sampling design is unbalanced with most of the data having been collected by scientific observers deployed on commercial large-scale longliners that contributed to `r round(ALB_FL_RD[FISHERY_CODE %in% c("LLD", "LLF"), .N] / ALB_FL_RD[, .N] * 100, 1)`% of the total data set. Samples from  fresh fish caught by Taiwanese, Japanese, and Chinese longliners represent the very large majority of the observer data available for the study. In the case of Japanese data, measurements of fork length were taken to the nearest 0.1 cm with tape, caliper and/or measuring board and round weights were mostly taken with 150 kg platform scales and beam scales and reported to the nearest 0.1 kg (_pers. com._ T. Nishida). Less information is available on the protocol used by observers in other longline fisheries. 

Other morphometric measurements for albacore caught in purse seine (n = `r prettyNum(ALB_FL_RD[FISHERY_GROUP_CODE == "PS", .N], big.mark = ",")`), longline (n = `r prettyNum(ALB_FL_RD[!SOURCE %in% c("IOTC HISTORICAL", "IOTC ROS", "OFDC", "SHOU") & FISHERY_GROUP_CODE == "LL", .N], big.mark = ",")`), and baitboat fisheries (n = `r prettyNum(ALB_FL_RD[FISHERY_GROUP_CODE == "BB", .N], big.mark = ",")`) were collected in processing factories located in Victoria (Seychelles), Le Port (La Réunion), Port Louis (Mauritius), and Cape Town (South Africa) as part of monitoring and research projects conducted in the region between `r ALB_FL_RD[!SOURCE %in% c("IOTC HISTORICAL", "IOTC ROS", "OFDC", "SHOU"), min(YEAR)]` and `r ALB_FL_RD[!SOURCE %in% c("IOTC HISTORICAL", "IOTC ROS", "OFDC", "SHOU"), max(YEAR)]` [@Chassot2014;@Bodin2018;@Dhurmeea2016;@Bonhommeau2018]. In addition, some samples (n = `r ALB_FL_RD[FISHERY_CODE %in% c("LIH", "LIT"), .N]`) were directly collected in the field for fish caught in coastal handline and trolling fisheries and landed in some local markets of Mauritius [@Dhurmeea2016].