# Results

### Non-linear models

The GAM including all covariates (Eq. \@ref(eq:gam5)) had the lowest AIC and explained most of the variability in the observed weights (**Table \@ref(tab:GAMsAICTable)**). The total deviance explained was `r round(summary(GAM5)$dev.expl*100, 1)`%.  Results showed that the relationship between fork length and round weight varies with sex, space, and time while the fleet and fishery have also an effect on morphometric parameters of Indian Ocean albacore (_p_-value< 0.001). The relationship shows some seasonal variations with the highest values of weight estimated in February-March and the lowest values in August (**Fig. \@ref(fig:GAMMonthEffect)**). The interaction between fork length and sex indicates that the relationship differs between males and females (**Fig. \@ref(fig:GAMFLSexEffect)**). Habitat explains some variability in the relationship, with increased weight at higher latitudes and some variability along the coasts of the Indian Ocean (**Fig. \@ref(fig:GAMLongLatSexEffect)**). Diagnostic plots are given in [Appendix I](#Diagnostics) and show some departure from the assumption of normality at the extremes, due to some variation in weight at length for very small and large fish, associated with sparse data (**Fig. \@ref(fig:DiagnosticGAM5)**).

### Linear models

The linear model including all covariates except fishery had the lowest AIC. All effects kept in the model were found to be highly statistically significant. However, each of them explained a small percentage of total variation as compared to fork length. After accounting for length, the most important effect explaining weight was the area of origin of the fish (**Table \@ref(tab:AnovaTableBestLM)**). The relationship was also found to vary with sex, with males having smaller weights than females.

The model including fork length and area as covariates explained `r round(summary(LM_ALB_FL_RD_AREA)$"adj.r.squared"*100, 1)`% of the deviance in the data. The effect of area was highly significant but explained only `r round(anova(LM_ALB_FL_RD_AREA)$"Sum Sq"[2]/sum(anova(LM_ALB_FL_RD_AREA)$"Sum Sq")*100, 2)`% of the total percentage of variation in the data. Weights predicted in area 2 were higher than in the other areas while predicted in areas 3 and 4 were very similar and the lowest (**Fig. \@ref(fig:ModelFitsByArea)**).

The model fitted to the overall data set that only considered fork length as covariate predicted lower weights than the relationship of Penney (1994) used in the stock assessment model in 2019 (**Fig. \@ref(fig:LMOnlyFL)**). The relationship was however very similar to the one derived by Kitakado et al. (2019) and used in the stock assessment in 2022 for the size range 50-90 cm, while it diverged from above 90 cm to predict smaller weights at larger sizes (**Fig. \@ref(fig:LMOnlyFL)** and **Table \@ref(tab:PredictionTable)**).

