# Discussion & perspectives

We collated a data set of almost half a million observations of fork length and round weight of albacore spanning more than two decades and spreading across the fishing grounds of albacore over the whole Indian Ocean. Data were collected with different protocols and most measurements were made on fresh fish at sea on longliners. Little information is available on the tools used to measure weight but ship motions at sea are known to affect the precision of weights measurements while initial data mining indicated that some weight data were inconsistent and possibly visually estimated by the observers. Stricter rules could be adopted to filter the data (e.g., based on Cook's distance) and remove the samples collected in the Atlantic Ocean regarding the large size of the data set in future analyses 

Including random effects in the GAMs would be useful to better account for co-dependence within samples [@Chang2022]. As part of this preliminary analysis, attempts were made to fit a random effect and allow the sampling strata (i.e., combination of year, month, latitude, longitude, and fleet) to affect the estimates of intercept terms but computation time was very long due to the large sample size. Sub-sampling the data set within each stratum might be a good way forward while an alternative statistical and estimation approach to account for the non-linear effects in the relationship could be envisaged [@Kristensen2016].