# Tables

```{r DataFieldsDefinitions, tab.cap = "Definition of the fields included in the albacore morphometric data set"}
FIELD_DEFINITIONS_FT
```

\pagebreak

```{r SamplingDesignTableSourceFisheryGroup, tab.cap = "Number of albacore samples (N) by data source, fleet, and fishery group along with the range of morphometric measurements for fork length (FL; cm) and round weight (RD; kg). OFDC = Overseas Fisheries Deveopment Council; SHOU = Shanghai Ocean University; UoM-IRD = University of Mauritius - Institut de Recherche pour le Développement"}
SAMPLING_DESIGN_TABLE_FG_SOURCE_FLEET_FT
```

\pagebreak

```{r GAMsAICTable, tab.cap = "Estimates of degrees of freedom (df) and values of Akaike Information Criterion (AIC) for the five Generalized Additive Models fitted to the fork length and round weight data of Indian Ocean albacore"}
AIC_TABLE_GAMS_FT 
```

\pagebreak

```{r AnovaTableBestLM, tab.cap = "Summary table of analysis of variance of the round weight of Indian Ocean albacore for the best linear model selected based on the lowest AIC. df = degrees of freedom"}
ANOVA_TABLE_LM_ALB_FL_RD_ALL_FINAL_FT
```

\pagebreak

```{r PredictionTable, tab.cap = "Weights (kg) predicted for a range of fork lengths (50-130 cm) based on the mean linear regression model fitted to all data with only fork length as covaruate (This study), the relationships used in the stock assessments (SA) performed in 2019 (Penney 1994) and 2022 (Kitakado et al. 2019), and the mean linear regression model including both fork length and areas used for CPUE analyses"}
PREDICTION_TABLES_WEIGHT_FT
```